'use client'

import type { Metadata } from 'next'
import { cn } from '@/utils/style'
import { Geist, Geist_Mono } from 'next/font/google'
import '@ant-design/v5-patch-for-react-19'
import '@/layouts/common/globals.css'
import '@/layouts/common/uno.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: FC = ({
  children
}) => {
  return (
    <html lang="en">
      <body className={cn(
        `${geistSans.variable} ${geistMono.variable}`,
        'bg-background text-text size-screen'
      )}
      >
        {children}
      </body>
    </html>
  )
}

export default RootLayout
