export enum ProfileTab {
  Overview = 'Overview',
  Edit = 'Edit',
  PropertyTokens = 'PropertyTokens',
  Earnings = 'Earnings',
  History = 'History',
  Recording = 'Recording',
  TransactionStatus = 'TransactionStatus',
  Assets = 'Assets',
  AssetsSummary = 'AssetsSummary',
  DistributionRecord = 'DistributionRecord',
  Message = 'Message',
  DividendStatistics = 'DividendStatistics',
  Appeal = 'Appeal',
  DefaultWarning = 'DefaultWarning',
  RedemptionList = 'RedemptionList',
  WarningInfo = 'WarningInfo',
  WarningRedemptionInfo = 'WarningRedemptionInfo',
  SaleRecord = 'SaleRecord'
}
