import type { Metadata } from 'next'
import { cn } from '@/utils/style'
import { Geist, Geist_Mono } from 'next/font/google'
import MainFooter from './footer'
import MainHeader from './header'

import '@/layouts/common/globals.css'
import '@/layouts/common/uno.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const MainLayout: FC = ({
  children
}) => {
  return (
    <html lang="en">
      <body className={cn(
        `${geistSans.variable} ${geistMono.variable}`,
        'bg-background text-text size-screen'
      )}
      >
        <MainHeader />
        <main className="mx-a max-w-7xl">
          {children}
        </main>
        <MainFooter />
      </body>
    </html>
  )
}

export default MainLayout
