/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppTransactionCreateBuyOrderIndexImport } from './routes/_app/transaction/create-buy-order/index'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/_app/')()
const AppPropertiesIndexLazyImport = createFileRoute('/_app/properties/')()
const AppProfileIndexLazyImport = createFileRoute('/_app/profile/')()
const AppNewsIndexLazyImport = createFileRoute('/_app/news/')()
const AppInvestmentIndexLazyImport = createFileRoute('/_app/investment/')()
const AppHomeIndexLazyImport = createFileRoute('/_app/home/')()
const AppHelpIndexLazyImport = createFileRoute('/_app/help/')()
const AppGuidanceIndexLazyImport = createFileRoute('/_app/guidance/')()
const AppAuditStatusIndexLazyImport = createFileRoute('/_app/auditStatus/')()
const AppAboutIndexLazyImport = createFileRoute('/_app/about/')()
const AppTransactionHashLazyImport = createFileRoute(
  '/_app/transaction/$hash',
)()
const AppBuyIdLazyImport = createFileRoute('/_app/buy/$id')()
const AppPropertiesInstitutionalIndexLazyImport = createFileRoute(
  '/_app/properties/institutional/',
)()
const AppAccountCreateIndexLazyImport = createFileRoute(
  '/_app/account/create/',
)()
const AppAccountCollectionsIndexLazyImport = createFileRoute(
  '/_app/account/collections/',
)()
const AppTransactionSellIdLazyImport = createFileRoute(
  '/_app/transaction/sell/$id',
)()
const AppTransactionRedemptionIdLazyImport = createFileRoute(
  '/_app/transaction/redemption/$id',
)()
const AppTransactionCreateSellOrderIdLazyImport = createFileRoute(
  '/_app/transaction/create-sell-order/$id',
)()
const AppTransactionBuyIdLazyImport = createFileRoute(
  '/_app/transaction/buy/$id',
)()
const AppPropertiesPaymentIdLazyImport = createFileRoute(
  '/_app/properties/payment/$id',
)()
const AppPropertiesDetailIdLazyImport = createFileRoute(
  '/_app/properties/detail/$id',
)()
const AppNewsDetailIdLazyImport = createFileRoute('/_app/news/detail/$id')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppPropertiesIndexLazyRoute = AppPropertiesIndexLazyImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/properties/index.lazy').then((d) => d.Route),
)

const AppProfileIndexLazyRoute = AppProfileIndexLazyImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/profile/index.lazy').then((d) => d.Route),
)

const AppNewsIndexLazyRoute = AppNewsIndexLazyImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/news/index.lazy').then((d) => d.Route),
)

const AppInvestmentIndexLazyRoute = AppInvestmentIndexLazyImport.update({
  id: '/investment/',
  path: '/investment/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/investment/index.lazy').then((d) => d.Route),
)

const AppHomeIndexLazyRoute = AppHomeIndexLazyImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/home/index.lazy').then((d) => d.Route),
)

const AppHelpIndexLazyRoute = AppHelpIndexLazyImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/help/index.lazy').then((d) => d.Route),
)

const AppGuidanceIndexLazyRoute = AppGuidanceIndexLazyImport.update({
  id: '/guidance/',
  path: '/guidance/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/guidance/index.lazy').then((d) => d.Route),
)

const AppAuditStatusIndexLazyRoute = AppAuditStatusIndexLazyImport.update({
  id: '/auditStatus/',
  path: '/auditStatus/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/auditStatus/index.lazy').then((d) => d.Route),
)

const AppAboutIndexLazyRoute = AppAboutIndexLazyImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/about/index.lazy').then((d) => d.Route),
)

const AppTransactionHashLazyRoute = AppTransactionHashLazyImport.update({
  id: '/transaction/$hash',
  path: '/transaction/$hash',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transaction/$hash.lazy').then((d) => d.Route),
)

const AppBuyIdLazyRoute = AppBuyIdLazyImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/buy/$id.lazy').then((d) => d.Route))

const AppPropertiesInstitutionalIndexLazyRoute =
  AppPropertiesInstitutionalIndexLazyImport.update({
    id: '/properties/institutional/',
    path: '/properties/institutional/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/properties/institutional/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppAccountCreateIndexLazyRoute = AppAccountCreateIndexLazyImport.update({
  id: '/account/create/',
  path: '/account/create/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/account/create/index.lazy').then((d) => d.Route),
)

const AppAccountCollectionsIndexLazyRoute =
  AppAccountCollectionsIndexLazyImport.update({
    id: '/account/collections/',
    path: '/account/collections/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/account/collections/index.lazy').then((d) => d.Route),
  )

const AppTransactionCreateBuyOrderIndexRoute =
  AppTransactionCreateBuyOrderIndexImport.update({
    id: '/transaction/create-buy-order/',
    path: '/transaction/create-buy-order/',
    getParentRoute: () => AppRoute,
  } as any)

const AppTransactionSellIdLazyRoute = AppTransactionSellIdLazyImport.update({
  id: '/transaction/sell/$id',
  path: '/transaction/sell/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transaction/sell/$id.lazy').then((d) => d.Route),
)

const AppTransactionRedemptionIdLazyRoute =
  AppTransactionRedemptionIdLazyImport.update({
    id: '/transaction/redemption/$id',
    path: '/transaction/redemption/$id',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/transaction/redemption/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AppTransactionCreateSellOrderIdLazyRoute =
  AppTransactionCreateSellOrderIdLazyImport.update({
    id: '/transaction/create-sell-order/$id',
    path: '/transaction/create-sell-order/$id',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/transaction/create-sell-order/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AppTransactionBuyIdLazyRoute = AppTransactionBuyIdLazyImport.update({
  id: '/transaction/buy/$id',
  path: '/transaction/buy/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transaction/buy/$id.lazy').then((d) => d.Route),
)

const AppPropertiesPaymentIdLazyRoute = AppPropertiesPaymentIdLazyImport.update(
  {
    id: '/properties/payment/$id',
    path: '/properties/payment/$id',
    getParentRoute: () => AppRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/properties/payment/$id.lazy').then((d) => d.Route),
)

const AppPropertiesDetailIdLazyRoute = AppPropertiesDetailIdLazyImport.update({
  id: '/properties/detail/$id',
  path: '/properties/detail/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/properties/detail/$id.lazy').then((d) => d.Route),
)

const AppNewsDetailIdLazyRoute = AppNewsDetailIdLazyImport.update({
  id: '/news/detail/$id',
  path: '/news/detail/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/news/detail/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/buy/$id': {
      id: '/_app/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof AppBuyIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/$hash': {
      id: '/_app/transaction/$hash'
      path: '/transaction/$hash'
      fullPath: '/transaction/$hash'
      preLoaderRoute: typeof AppTransactionHashLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/auditStatus/': {
      id: '/_app/auditStatus/'
      path: '/auditStatus'
      fullPath: '/auditStatus'
      preLoaderRoute: typeof AppAuditStatusIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/guidance/': {
      id: '/_app/guidance/'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof AppGuidanceIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/help/': {
      id: '/_app/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/investment/': {
      id: '/_app/investment/'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof AppInvestmentIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/news/detail/$id': {
      id: '/_app/news/detail/$id'
      path: '/news/detail/$id'
      fullPath: '/news/detail/$id'
      preLoaderRoute: typeof AppNewsDetailIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/detail/$id': {
      id: '/_app/properties/detail/$id'
      path: '/properties/detail/$id'
      fullPath: '/properties/detail/$id'
      preLoaderRoute: typeof AppPropertiesDetailIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/payment/$id': {
      id: '/_app/properties/payment/$id'
      path: '/properties/payment/$id'
      fullPath: '/properties/payment/$id'
      preLoaderRoute: typeof AppPropertiesPaymentIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/buy/$id': {
      id: '/_app/transaction/buy/$id'
      path: '/transaction/buy/$id'
      fullPath: '/transaction/buy/$id'
      preLoaderRoute: typeof AppTransactionBuyIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/create-sell-order/$id': {
      id: '/_app/transaction/create-sell-order/$id'
      path: '/transaction/create-sell-order/$id'
      fullPath: '/transaction/create-sell-order/$id'
      preLoaderRoute: typeof AppTransactionCreateSellOrderIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/redemption/$id': {
      id: '/_app/transaction/redemption/$id'
      path: '/transaction/redemption/$id'
      fullPath: '/transaction/redemption/$id'
      preLoaderRoute: typeof AppTransactionRedemptionIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/sell/$id': {
      id: '/_app/transaction/sell/$id'
      path: '/transaction/sell/$id'
      fullPath: '/transaction/sell/$id'
      preLoaderRoute: typeof AppTransactionSellIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/create-buy-order/': {
      id: '/_app/transaction/create-buy-order/'
      path: '/transaction/create-buy-order'
      fullPath: '/transaction/create-buy-order'
      preLoaderRoute: typeof AppTransactionCreateBuyOrderIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/account/collections/': {
      id: '/_app/account/collections/'
      path: '/account/collections'
      fullPath: '/account/collections'
      preLoaderRoute: typeof AppAccountCollectionsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/account/create/': {
      id: '/_app/account/create/'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof AppAccountCreateIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/institutional/': {
      id: '/_app/properties/institutional/'
      path: '/properties/institutional'
      fullPath: '/properties/institutional'
      preLoaderRoute: typeof AppPropertiesInstitutionalIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppBuyIdLazyRoute: typeof AppBuyIdLazyRoute
  AppTransactionHashLazyRoute: typeof AppTransactionHashLazyRoute
  AppAboutIndexLazyRoute: typeof AppAboutIndexLazyRoute
  AppAuditStatusIndexLazyRoute: typeof AppAuditStatusIndexLazyRoute
  AppGuidanceIndexLazyRoute: typeof AppGuidanceIndexLazyRoute
  AppHelpIndexLazyRoute: typeof AppHelpIndexLazyRoute
  AppHomeIndexLazyRoute: typeof AppHomeIndexLazyRoute
  AppInvestmentIndexLazyRoute: typeof AppInvestmentIndexLazyRoute
  AppNewsIndexLazyRoute: typeof AppNewsIndexLazyRoute
  AppProfileIndexLazyRoute: typeof AppProfileIndexLazyRoute
  AppPropertiesIndexLazyRoute: typeof AppPropertiesIndexLazyRoute
  AppNewsDetailIdLazyRoute: typeof AppNewsDetailIdLazyRoute
  AppPropertiesDetailIdLazyRoute: typeof AppPropertiesDetailIdLazyRoute
  AppPropertiesPaymentIdLazyRoute: typeof AppPropertiesPaymentIdLazyRoute
  AppTransactionBuyIdLazyRoute: typeof AppTransactionBuyIdLazyRoute
  AppTransactionCreateSellOrderIdLazyRoute: typeof AppTransactionCreateSellOrderIdLazyRoute
  AppTransactionRedemptionIdLazyRoute: typeof AppTransactionRedemptionIdLazyRoute
  AppTransactionSellIdLazyRoute: typeof AppTransactionSellIdLazyRoute
  AppTransactionCreateBuyOrderIndexRoute: typeof AppTransactionCreateBuyOrderIndexRoute
  AppAccountCollectionsIndexLazyRoute: typeof AppAccountCollectionsIndexLazyRoute
  AppAccountCreateIndexLazyRoute: typeof AppAccountCreateIndexLazyRoute
  AppPropertiesInstitutionalIndexLazyRoute: typeof AppPropertiesInstitutionalIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppBuyIdLazyRoute: AppBuyIdLazyRoute,
  AppTransactionHashLazyRoute: AppTransactionHashLazyRoute,
  AppAboutIndexLazyRoute: AppAboutIndexLazyRoute,
  AppAuditStatusIndexLazyRoute: AppAuditStatusIndexLazyRoute,
  AppGuidanceIndexLazyRoute: AppGuidanceIndexLazyRoute,
  AppHelpIndexLazyRoute: AppHelpIndexLazyRoute,
  AppHomeIndexLazyRoute: AppHomeIndexLazyRoute,
  AppInvestmentIndexLazyRoute: AppInvestmentIndexLazyRoute,
  AppNewsIndexLazyRoute: AppNewsIndexLazyRoute,
  AppProfileIndexLazyRoute: AppProfileIndexLazyRoute,
  AppPropertiesIndexLazyRoute: AppPropertiesIndexLazyRoute,
  AppNewsDetailIdLazyRoute: AppNewsDetailIdLazyRoute,
  AppPropertiesDetailIdLazyRoute: AppPropertiesDetailIdLazyRoute,
  AppPropertiesPaymentIdLazyRoute: AppPropertiesPaymentIdLazyRoute,
  AppTransactionBuyIdLazyRoute: AppTransactionBuyIdLazyRoute,
  AppTransactionCreateSellOrderIdLazyRoute:
    AppTransactionCreateSellOrderIdLazyRoute,
  AppTransactionRedemptionIdLazyRoute: AppTransactionRedemptionIdLazyRoute,
  AppTransactionSellIdLazyRoute: AppTransactionSellIdLazyRoute,
  AppTransactionCreateBuyOrderIndexRoute:
    AppTransactionCreateBuyOrderIndexRoute,
  AppAccountCollectionsIndexLazyRoute: AppAccountCollectionsIndexLazyRoute,
  AppAccountCreateIndexLazyRoute: AppAccountCreateIndexLazyRoute,
  AppPropertiesInstitutionalIndexLazyRoute:
    AppPropertiesInstitutionalIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexLazyRoute
  '/buy/$id': typeof AppBuyIdLazyRoute
  '/transaction/$hash': typeof AppTransactionHashLazyRoute
  '/about': typeof AppAboutIndexLazyRoute
  '/auditStatus': typeof AppAuditStatusIndexLazyRoute
  '/guidance': typeof AppGuidanceIndexLazyRoute
  '/help': typeof AppHelpIndexLazyRoute
  '/home': typeof AppHomeIndexLazyRoute
  '/investment': typeof AppInvestmentIndexLazyRoute
  '/news': typeof AppNewsIndexLazyRoute
  '/profile': typeof AppProfileIndexLazyRoute
  '/properties': typeof AppPropertiesIndexLazyRoute
  '/news/detail/$id': typeof AppNewsDetailIdLazyRoute
  '/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/transaction/buy/$id': typeof AppTransactionBuyIdLazyRoute
  '/transaction/create-sell-order/$id': typeof AppTransactionCreateSellOrderIdLazyRoute
  '/transaction/redemption/$id': typeof AppTransactionRedemptionIdLazyRoute
  '/transaction/sell/$id': typeof AppTransactionSellIdLazyRoute
  '/transaction/create-buy-order': typeof AppTransactionCreateBuyOrderIndexRoute
  '/account/collections': typeof AppAccountCollectionsIndexLazyRoute
  '/account/create': typeof AppAccountCreateIndexLazyRoute
  '/properties/institutional': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexLazyRoute
  '/buy/$id': typeof AppBuyIdLazyRoute
  '/transaction/$hash': typeof AppTransactionHashLazyRoute
  '/about': typeof AppAboutIndexLazyRoute
  '/auditStatus': typeof AppAuditStatusIndexLazyRoute
  '/guidance': typeof AppGuidanceIndexLazyRoute
  '/help': typeof AppHelpIndexLazyRoute
  '/home': typeof AppHomeIndexLazyRoute
  '/investment': typeof AppInvestmentIndexLazyRoute
  '/news': typeof AppNewsIndexLazyRoute
  '/profile': typeof AppProfileIndexLazyRoute
  '/properties': typeof AppPropertiesIndexLazyRoute
  '/news/detail/$id': typeof AppNewsDetailIdLazyRoute
  '/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/transaction/buy/$id': typeof AppTransactionBuyIdLazyRoute
  '/transaction/create-sell-order/$id': typeof AppTransactionCreateSellOrderIdLazyRoute
  '/transaction/redemption/$id': typeof AppTransactionRedemptionIdLazyRoute
  '/transaction/sell/$id': typeof AppTransactionSellIdLazyRoute
  '/transaction/create-buy-order': typeof AppTransactionCreateBuyOrderIndexRoute
  '/account/collections': typeof AppAccountCollectionsIndexLazyRoute
  '/account/create': typeof AppAccountCreateIndexLazyRoute
  '/properties/institutional': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexLazyRoute
  '/_app/buy/$id': typeof AppBuyIdLazyRoute
  '/_app/transaction/$hash': typeof AppTransactionHashLazyRoute
  '/_app/about/': typeof AppAboutIndexLazyRoute
  '/_app/auditStatus/': typeof AppAuditStatusIndexLazyRoute
  '/_app/guidance/': typeof AppGuidanceIndexLazyRoute
  '/_app/help/': typeof AppHelpIndexLazyRoute
  '/_app/home/': typeof AppHomeIndexLazyRoute
  '/_app/investment/': typeof AppInvestmentIndexLazyRoute
  '/_app/news/': typeof AppNewsIndexLazyRoute
  '/_app/profile/': typeof AppProfileIndexLazyRoute
  '/_app/properties/': typeof AppPropertiesIndexLazyRoute
  '/_app/news/detail/$id': typeof AppNewsDetailIdLazyRoute
  '/_app/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/_app/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/_app/transaction/buy/$id': typeof AppTransactionBuyIdLazyRoute
  '/_app/transaction/create-sell-order/$id': typeof AppTransactionCreateSellOrderIdLazyRoute
  '/_app/transaction/redemption/$id': typeof AppTransactionRedemptionIdLazyRoute
  '/_app/transaction/sell/$id': typeof AppTransactionSellIdLazyRoute
  '/_app/transaction/create-buy-order/': typeof AppTransactionCreateBuyOrderIndexRoute
  '/_app/account/collections/': typeof AppAccountCollectionsIndexLazyRoute
  '/_app/account/create/': typeof AppAccountCreateIndexLazyRoute
  '/_app/properties/institutional/': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/buy/$id'
    | '/transaction/$hash'
    | '/about'
    | '/auditStatus'
    | '/guidance'
    | '/help'
    | '/home'
    | '/investment'
    | '/news'
    | '/profile'
    | '/properties'
    | '/news/detail/$id'
    | '/properties/detail/$id'
    | '/properties/payment/$id'
    | '/transaction/buy/$id'
    | '/transaction/create-sell-order/$id'
    | '/transaction/redemption/$id'
    | '/transaction/sell/$id'
    | '/transaction/create-buy-order'
    | '/account/collections'
    | '/account/create'
    | '/properties/institutional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy/$id'
    | '/transaction/$hash'
    | '/about'
    | '/auditStatus'
    | '/guidance'
    | '/help'
    | '/home'
    | '/investment'
    | '/news'
    | '/profile'
    | '/properties'
    | '/news/detail/$id'
    | '/properties/detail/$id'
    | '/properties/payment/$id'
    | '/transaction/buy/$id'
    | '/transaction/create-sell-order/$id'
    | '/transaction/redemption/$id'
    | '/transaction/sell/$id'
    | '/transaction/create-buy-order'
    | '/account/collections'
    | '/account/create'
    | '/properties/institutional'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/buy/$id'
    | '/_app/transaction/$hash'
    | '/_app/about/'
    | '/_app/auditStatus/'
    | '/_app/guidance/'
    | '/_app/help/'
    | '/_app/home/'
    | '/_app/investment/'
    | '/_app/news/'
    | '/_app/profile/'
    | '/_app/properties/'
    | '/_app/news/detail/$id'
    | '/_app/properties/detail/$id'
    | '/_app/properties/payment/$id'
    | '/_app/transaction/buy/$id'
    | '/_app/transaction/create-sell-order/$id'
    | '/_app/transaction/redemption/$id'
    | '/_app/transaction/sell/$id'
    | '/_app/transaction/create-buy-order/'
    | '/_app/account/collections/'
    | '/_app/account/create/'
    | '/_app/properties/institutional/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/buy/$id",
        "/_app/transaction/$hash",
        "/_app/about/",
        "/_app/auditStatus/",
        "/_app/guidance/",
        "/_app/help/",
        "/_app/home/",
        "/_app/investment/",
        "/_app/news/",
        "/_app/profile/",
        "/_app/properties/",
        "/_app/news/detail/$id",
        "/_app/properties/detail/$id",
        "/_app/properties/payment/$id",
        "/_app/transaction/buy/$id",
        "/_app/transaction/create-sell-order/$id",
        "/_app/transaction/redemption/$id",
        "/_app/transaction/sell/$id",
        "/_app/transaction/create-buy-order/",
        "/_app/account/collections/",
        "/_app/account/create/",
        "/_app/properties/institutional/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/buy/$id": {
      "filePath": "_app/buy/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/$hash": {
      "filePath": "_app/transaction/$hash.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/about/": {
      "filePath": "_app/about/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/auditStatus/": {
      "filePath": "_app/auditStatus/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/guidance/": {
      "filePath": "_app/guidance/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/help/": {
      "filePath": "_app/help/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/home/": {
      "filePath": "_app/home/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/investment/": {
      "filePath": "_app/investment/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/news/": {
      "filePath": "_app/news/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/": {
      "filePath": "_app/properties/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/news/detail/$id": {
      "filePath": "_app/news/detail/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/detail/$id": {
      "filePath": "_app/properties/detail/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/payment/$id": {
      "filePath": "_app/properties/payment/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/buy/$id": {
      "filePath": "_app/transaction/buy/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/create-sell-order/$id": {
      "filePath": "_app/transaction/create-sell-order/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/redemption/$id": {
      "filePath": "_app/transaction/redemption/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/sell/$id": {
      "filePath": "_app/transaction/sell/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/create-buy-order/": {
      "filePath": "_app/transaction/create-buy-order/index.tsx",
      "parent": "/_app"
    },
    "/_app/account/collections/": {
      "filePath": "_app/account/collections/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/account/create/": {
      "filePath": "_app/account/create/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/institutional/": {
      "filePath": "_app/properties/institutional/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
