/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/_app/')()
const AppPropertiesIndexLazyImport = createFileRoute('/_app/properties/')()
const AppProfileIndexLazyImport = createFileRoute('/_app/profile/')()
const AppInvestmentIndexLazyImport = createFileRoute('/_app/investment/')()
const AppHomeIndexLazyImport = createFileRoute('/_app/home/')()
const AppAboutIndexLazyImport = createFileRoute('/_app/about/')()
const AppTransactionIdLazyImport = createFileRoute('/_app/transaction/$id')()
const AppPropertiesInstitutionalIndexLazyImport = createFileRoute(
  '/_app/properties/institutional/',
)()
const AppAccountCreateIndexLazyImport = createFileRoute(
  '/_app/account/create/',
)()
const AppAccountCollectionsIndexLazyImport = createFileRoute(
  '/_app/account/collections/',
)()
const AppPropertiesPaymentIdLazyImport = createFileRoute(
  '/_app/properties/payment/$id',
)()
const AppPropertiesDetailIdLazyImport = createFileRoute(
  '/_app/properties/detail/$id',
)()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppPropertiesIndexLazyRoute = AppPropertiesIndexLazyImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/properties/index.lazy').then((d) => d.Route),
)

const AppProfileIndexLazyRoute = AppProfileIndexLazyImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/profile/index.lazy').then((d) => d.Route),
)

const AppInvestmentIndexLazyRoute = AppInvestmentIndexLazyImport.update({
  id: '/investment/',
  path: '/investment/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/investment/index.lazy').then((d) => d.Route),
)

const AppHomeIndexLazyRoute = AppHomeIndexLazyImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/home/index.lazy').then((d) => d.Route),
)

const AppAboutIndexLazyRoute = AppAboutIndexLazyImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/about/index.lazy').then((d) => d.Route),
)

const AppTransactionIdLazyRoute = AppTransactionIdLazyImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transaction/$id.lazy').then((d) => d.Route),
)

const AppPropertiesInstitutionalIndexLazyRoute =
  AppPropertiesInstitutionalIndexLazyImport.update({
    id: '/properties/institutional/',
    path: '/properties/institutional/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/properties/institutional/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppAccountCreateIndexLazyRoute = AppAccountCreateIndexLazyImport.update({
  id: '/account/create/',
  path: '/account/create/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/account/create/index.lazy').then((d) => d.Route),
)

const AppAccountCollectionsIndexLazyRoute =
  AppAccountCollectionsIndexLazyImport.update({
    id: '/account/collections/',
    path: '/account/collections/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/account/collections/index.lazy').then((d) => d.Route),
  )

const AppPropertiesPaymentIdLazyRoute = AppPropertiesPaymentIdLazyImport.update(
  {
    id: '/properties/payment/$id',
    path: '/properties/payment/$id',
    getParentRoute: () => AppRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/properties/payment/$id.lazy').then((d) => d.Route),
)

const AppPropertiesDetailIdLazyRoute = AppPropertiesDetailIdLazyImport.update({
  id: '/properties/detail/$id',
  path: '/properties/detail/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/properties/detail/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/transaction/$id': {
      id: '/_app/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof AppTransactionIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/investment/': {
      id: '/_app/investment/'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof AppInvestmentIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/detail/$id': {
      id: '/_app/properties/detail/$id'
      path: '/properties/detail/$id'
      fullPath: '/properties/detail/$id'
      preLoaderRoute: typeof AppPropertiesDetailIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/payment/$id': {
      id: '/_app/properties/payment/$id'
      path: '/properties/payment/$id'
      fullPath: '/properties/payment/$id'
      preLoaderRoute: typeof AppPropertiesPaymentIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/account/collections/': {
      id: '/_app/account/collections/'
      path: '/account/collections'
      fullPath: '/account/collections'
      preLoaderRoute: typeof AppAccountCollectionsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/account/create/': {
      id: '/_app/account/create/'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof AppAccountCreateIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/properties/institutional/': {
      id: '/_app/properties/institutional/'
      path: '/properties/institutional'
      fullPath: '/properties/institutional'
      preLoaderRoute: typeof AppPropertiesInstitutionalIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppTransactionIdLazyRoute: typeof AppTransactionIdLazyRoute
  AppAboutIndexLazyRoute: typeof AppAboutIndexLazyRoute
  AppHomeIndexLazyRoute: typeof AppHomeIndexLazyRoute
  AppInvestmentIndexLazyRoute: typeof AppInvestmentIndexLazyRoute
  AppProfileIndexLazyRoute: typeof AppProfileIndexLazyRoute
  AppPropertiesIndexLazyRoute: typeof AppPropertiesIndexLazyRoute
  AppPropertiesDetailIdLazyRoute: typeof AppPropertiesDetailIdLazyRoute
  AppPropertiesPaymentIdLazyRoute: typeof AppPropertiesPaymentIdLazyRoute
  AppAccountCollectionsIndexLazyRoute: typeof AppAccountCollectionsIndexLazyRoute
  AppAccountCreateIndexLazyRoute: typeof AppAccountCreateIndexLazyRoute
  AppPropertiesInstitutionalIndexLazyRoute: typeof AppPropertiesInstitutionalIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppTransactionIdLazyRoute: AppTransactionIdLazyRoute,
  AppAboutIndexLazyRoute: AppAboutIndexLazyRoute,
  AppHomeIndexLazyRoute: AppHomeIndexLazyRoute,
  AppInvestmentIndexLazyRoute: AppInvestmentIndexLazyRoute,
  AppProfileIndexLazyRoute: AppProfileIndexLazyRoute,
  AppPropertiesIndexLazyRoute: AppPropertiesIndexLazyRoute,
  AppPropertiesDetailIdLazyRoute: AppPropertiesDetailIdLazyRoute,
  AppPropertiesPaymentIdLazyRoute: AppPropertiesPaymentIdLazyRoute,
  AppAccountCollectionsIndexLazyRoute: AppAccountCollectionsIndexLazyRoute,
  AppAccountCreateIndexLazyRoute: AppAccountCreateIndexLazyRoute,
  AppPropertiesInstitutionalIndexLazyRoute:
    AppPropertiesInstitutionalIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexLazyRoute
  '/transaction/$id': typeof AppTransactionIdLazyRoute
  '/about': typeof AppAboutIndexLazyRoute
  '/home': typeof AppHomeIndexLazyRoute
  '/investment': typeof AppInvestmentIndexLazyRoute
  '/profile': typeof AppProfileIndexLazyRoute
  '/properties': typeof AppPropertiesIndexLazyRoute
  '/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/account/collections': typeof AppAccountCollectionsIndexLazyRoute
  '/account/create': typeof AppAccountCreateIndexLazyRoute
  '/properties/institutional': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexLazyRoute
  '/transaction/$id': typeof AppTransactionIdLazyRoute
  '/about': typeof AppAboutIndexLazyRoute
  '/home': typeof AppHomeIndexLazyRoute
  '/investment': typeof AppInvestmentIndexLazyRoute
  '/profile': typeof AppProfileIndexLazyRoute
  '/properties': typeof AppPropertiesIndexLazyRoute
  '/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/account/collections': typeof AppAccountCollectionsIndexLazyRoute
  '/account/create': typeof AppAccountCreateIndexLazyRoute
  '/properties/institutional': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexLazyRoute
  '/_app/transaction/$id': typeof AppTransactionIdLazyRoute
  '/_app/about/': typeof AppAboutIndexLazyRoute
  '/_app/home/': typeof AppHomeIndexLazyRoute
  '/_app/investment/': typeof AppInvestmentIndexLazyRoute
  '/_app/profile/': typeof AppProfileIndexLazyRoute
  '/_app/properties/': typeof AppPropertiesIndexLazyRoute
  '/_app/properties/detail/$id': typeof AppPropertiesDetailIdLazyRoute
  '/_app/properties/payment/$id': typeof AppPropertiesPaymentIdLazyRoute
  '/_app/account/collections/': typeof AppAccountCollectionsIndexLazyRoute
  '/_app/account/create/': typeof AppAccountCreateIndexLazyRoute
  '/_app/properties/institutional/': typeof AppPropertiesInstitutionalIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/transaction/$id'
    | '/about'
    | '/home'
    | '/investment'
    | '/profile'
    | '/properties'
    | '/properties/detail/$id'
    | '/properties/payment/$id'
    | '/account/collections'
    | '/account/create'
    | '/properties/institutional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transaction/$id'
    | '/about'
    | '/home'
    | '/investment'
    | '/profile'
    | '/properties'
    | '/properties/detail/$id'
    | '/properties/payment/$id'
    | '/account/collections'
    | '/account/create'
    | '/properties/institutional'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/transaction/$id'
    | '/_app/about/'
    | '/_app/home/'
    | '/_app/investment/'
    | '/_app/profile/'
    | '/_app/properties/'
    | '/_app/properties/detail/$id'
    | '/_app/properties/payment/$id'
    | '/_app/account/collections/'
    | '/_app/account/create/'
    | '/_app/properties/institutional/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/transaction/$id",
        "/_app/about/",
        "/_app/home/",
        "/_app/investment/",
        "/_app/profile/",
        "/_app/properties/",
        "/_app/properties/detail/$id",
        "/_app/properties/payment/$id",
        "/_app/account/collections/",
        "/_app/account/create/",
        "/_app/properties/institutional/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/transaction/$id": {
      "filePath": "_app/transaction/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/about/": {
      "filePath": "_app/about/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/home/": {
      "filePath": "_app/home/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/investment/": {
      "filePath": "_app/investment/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/": {
      "filePath": "_app/properties/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/detail/$id": {
      "filePath": "_app/properties/detail/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/payment/$id": {
      "filePath": "_app/properties/payment/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/account/collections/": {
      "filePath": "_app/account/collections/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/account/create/": {
      "filePath": "_app/account/create/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/properties/institutional/": {
      "filePath": "_app/properties/institutional/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
